<?php

/*
 * Implementation of hook_form_alter().
 */

function roblib_responsive_menu_form_block_admin_configure_alter(&$form, &$form_state) {

  $delta = $form['delta']['#value'];

  if (array_key_exists('superfish_name_' . $delta, $form['settings'])) {

    $form['settings']['sf-settings']['roblib_responsive_menu_toggle_' . $delta] = array(
      '#type' => 'checkbox',
      '#title' => t('Enable Responsive Menu'),
      '#default_value' => variable_get('roblib_responsive_menu_toggle_' . $delta, 0),
      '#description' => t('If enabled, set a breakpoint and type of responsive menu.'),
    );

    $form['settings']['sf-settings']['roblib_responsive_menu_breakpoint_' . $delta] = array(
      '#type' => 'textfield',
      '#title' => t('Enable Responsive Menu'),
      '#default_value' => variable_get('roblib_responsive_menu_breakpoint_' . $delta, '800px'),
      '#size'          => 5,
      '#maxlength'     => 10,
      '#description' => t('If responsive menu is enabled, set a max breakpoint size.'),
      '#prefix'        => '<div id="div-rrm-breakopoint-collapse">',
      // Jquery hook to show/hide optional widgets.
    );

    $form['#submit'][] = 'roblib_responsive_menu_submit';

  }

}


/*
 * Custom submit handler
 */

function roblib_responsive_menu_submit(&$form, &$form_state) {

  $delta = $form['delta']['#value'];

  variable_set('roblib_responsive_menu_toggle_' . $delta, $form_state['values']['roblib_responsive_menu_toggle_' . $delta]);
  variable_set('roblib_responsive_menu_breakpoint_' . $delta, $form_state['values']['roblib_responsive_menu_breakpoint_' . $delta]);

}

/*
* Implementation of hook_block_view_alter().
*/

function roblib_responsive_menu_block_view_alter(&$data, $block) {

  if ($block->module == 'superfish') {

    $delta = $block->delta;
    if (variable_get('roblib_responsive_menu_toggle_' . $delta) == '1') {

      $name = '';
      if (!empty($data['content'])) {

        $data['content'] = array(
          '#markup' => '<div class="roblib-responsive-menu-' . $delta . '">' . $data['content'] . '</div>');

        $data['content']['#attached']['css'] = array(
            'data' => drupal_get_path('module', 'roblib_responsive_menu') . '/css/roblib-responsive-select-menu.css',
            'options' => array(
              'group' => CSS_THEME,
              'every_page' => FALSE,
              'media' => 'screen',
              'preprocess' => FALSE,
              'weight' => '9999',
        ));

        if (isset($data['subject'])) {
          $name = $data['subject'];
        } else {
          $name = '';
        }

        $breakpoint = variable_get('roblib_responsive_menu_breakpoint_' . $delta);

        if ($delta < 5) {
        drupal_add_css(drupal_get_path('module', 'roblib_responsive_menu') .'/css/roblib-responsive-select-menu--mq-'.$delta.'.css',
          array(
            'group' => CSS_THEME,
            'every_page' => FALSE,
            'media' => 'screen and (max-width: ' . $breakpoint . ')',
            'preprocess' => FALSE,
            'weight' => '9999',
          ));
        } else {
          drupal_set_message(t('Responsive Select Menu supports a max of 4 menus.'), 'warning');
        }
        drupal_add_js(drupal_get_path('module', 'roblib_responsive_menu') .'/js/jquery.mobilemenu.js', array('scope' => 'footer', 'weight' => 6));
        drupal_add_js('jQuery(function(){jQuery(\'#superfish-'.$delta.'\').mobileMenu({menuID:'.$delta.',combine:false,prependTo:\'div.roblib-responsive-menu-'.$delta.'\'}); });',
          array('type' => 'inline', 'scope' => 'footer', 'weight' => 7));

      }

    }
  }

}
